name: Pipeline Movie App

on:
  push:
    branches: [ "ci/cd", "main", "master" ]
  pull_request:
    branches: [ "ci/cd", "main", "master" ]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build